#!/bin/sh

# default features
APPNAME=kksdcmd
EXECUTABLE=${APPNAME}
LOGLEVEL=5
EXTRAOPTS=

# upgrade from SD card
CARDMOUNTPOINT=/mnt/sda1
UPDATEIMAGE=kks-dcm.sysupgrade.bin

# card-based website
CARDWEBSITE=www
CARDWEBINDEX=index.html
CARDWEBDEFAULTINDEX="/www/sd_default_index.html"


# Allow overriding options
# - override from flash
if [ -e /flash/${APPNAME}_debug ]; then
  source /flash/${APPNAME}_debug
fi
# - override from tmp
if [ -e /tmp/${APPNAME}_debug ]; then
  source /tmp/${APPNAME}_debug
fi


if [ -d "${CARDMOUNTPOINT}" ]; then
  # SD card mounted - if there is no website on the SD card yet, install one
  if [ ! -d "${CARDMOUNTPOINT}/${CARDWEBSITE}" ]; then
    mkdir "${CARDMOUNTPOINT}/${CARDWEBSITE}"
  fi
  if [ ! -f "${CARDMOUNTPOINT}/${CARDWEBSITE}/${CARDWEBINDEX}" ]; then
    # copy default card-based index.html
    cp "${CARDWEBDEFAULTINDEX}" "${CARDMOUNTPOINT}/${CARDWEBSITE}/${CARDWEBINDEX}"
  fi
fi


# check for system upgrade delivered on SD card
if [ -f "${CARDMOUNTPOINT}/${UPDATEIMAGE}" ]; then
  rm "${CARDMOUNTPOINT}/${UPDATEIMAGE}_DONE"
  cp "${CARDMOUNTPOINT}/${UPDATEIMAGE}" /tmp/fwimg.img
  mv "${CARDMOUNTPOINT}/${UPDATEIMAGE}" "${CARDMOUNTPOINT}/${UPDATEIMAGE}_DONE"
  sync
  sleep 2
  cd /tmp
  sysupgrade /tmp/fwimg.img
  # should not exit, if it does - waaaaait
  sleep 600
  exit 0
fi

# normally run the daemon
exec ${EXECUTABLE} \
  --userlevel 2 \
  --ubusapi \
  --mainscript mainscript.txt \
  --datapath /flash \
  --resourcepath /usr/share/kksdcm \
  --corespi 10 \
  --modbus 0.0.0.0:502 \
  -l ${LOGLEVEL} \
  ${EXTRAOPTS} \
  </dev/null
