#!/bin/sh /etc/rc.common
# Copyright (c) 2016 plan44.ch/luz
START=99

boot() {

  echo "[p44bandit] configuring hardware"

  # GPIO18/19 as GPIO, not Ethernet
  devmem 0x1000003C 32 0x00FE01FF

  echo "[p44bandit] preparing for runit"

  # softlink all runit supervise dirs to /var/run
  PREV=$(pwd)
  cd /etc/service
  SERVICES=*
  mkdir -v -p /var/run/runit
  for SERV in ${SERVICES}; do
    # create softlink if not yet existing
    if [ ! -h /etc/service/${SERV}/supervise ]; then
      rm -v -r /etc/service/${SERV}/supervise
      ln -v -s -f /var/run/runit/supervise.${SERV} /etc/service/${SERV}/supervise
    fi
    # check for log
    if [ -d /etc/service/${SERV}/log ]; then
      # create softlink if not yet existing
      if [ ! -h /etc/service/${SERV}/log/supervise ]; then
        rm -v -r /etc/service/${SERV}/log/supervise
        ln -v -s -f /var/run/runit/supervise.${SERV}.log /etc/service/${SERV}/log/supervise
      fi
    fi
  done
  cd ${PREV}

  # make sure no dhcp services (v4, v6) or RA are running at all
  # - in case a dhcp section exists for lan
  uci set dhcp.lan.dhcpv4=disabled
  uci set dhcp.lan.dhcpv6=disabled
  uci set dhcp.lan.ra=disabled
  uci set dhcp.lan.ignore=1
  # - in case a dhcp section exists for wlan
  uci set dhcp.wlan.dhcpv4=disabled
  uci set dhcp.wlan.dhcpv6=disabled
  uci set dhcp.wlan.ra=disabled
  uci set dhcp.wlan.ignore=1
  uci commit dhcp

  # update host name
  UNIT_HOSTNAME="p44bandit"
  uci set system.@system[0].hostname="${UNIT_HOSTNAME}"
  uci commit system

  # start runit
  /sbin/runsvdir-start &
}
