#!/bin/sh

# ACTION=ifup|ifdown, INTERFACE=lan|wlan|..., DEVICE=eth0|wlan0|...
if [ "$ACTION" = ifup ]; then
  if [ "$INTERFACE" = lan -o "$DEVICE" = wlan ]; then
    # - report firmware if updated new
    if [ -e /flash/fw_updated ]; then
      # if firmware was newly installed, register with update server
      p44maintd --checkforupdate </dev/null >/dev/null 2>&1
      if [ $? -eq 0 ]; then
        # successfully checked (no network error) -> remove flag file
        rm /flash/fw_updated
      fi
    fi
  fi
fi
