#!/bin/sh

DAEMON=p44featured

# app config
APPCONFIG="--mainscript lethd_main.txt"

# basic config Omega2 on ledcontroller v1

# - PWM0 for LED dimming FET with 320uS = 3kHz period
PWM_LED_FET_PIN="pwmchip0.0.320000"

# - LED chain
MAX_LEDS=800
LED_TYPE="WS2813.GRB"
LEDCHAIN_NAME_1="ledchain1"
LEDCHAIN_NAME_2="ledchain2"
LEDCHAIN_NAME_3="ledchain3"
# - default ledchain init-params
#   [ledtype:[leddevicename:]]numberOfLeds:[x:dx:y:dy:firstoffset:betweenoffset][XYSA][W#whitecolor]
LEDCHAIN_DEVICE_1="${LED_TYPE}:/dev/${LEDCHAIN_NAME_1}:518:0:72:0:7:1:2:A"
LEDCHAIN_DEVICE_2="${LED_TYPE}:/dev/${LEDCHAIN_NAME_2}:182:0:24:0:7:1:2:A"
LEDCHAIN_DEVICE_3="${LED_TYPE}:/dev/${LEDCHAIN_NAME_3}:100"
LEDCHAINS="--ledchain ${LEDCHAIN_DEVICE_1} --ledchain ${LEDCHAIN_DEVICE_2} --ledchain ${LEDCHAIN_DEVICE_3}"

# - WiFi interface
WIFI_MONITOR_IF="moni0"
WIFITRACK=
if [ -f "/flash/wifitrack" ]; then
  if ! ip link | grep -q "${WIFI_MONITOR_IF}"; then
    # add monitor interface
    iw phy phy0 interface add "${WIFI_MONITOR_IF}" type monitor
    # activate it
    ip link set "${WIFI_MONITOR_IF}" up
  fi
  WIFITRACK="--wifimonif ${WIFI_MONITOR_IF}"
fi


# - Analog input (/dev/spidev1.0 software SPI)
ADC_INPUT_CH0="spi10.MCP3002@0.0"
ADC_INPUT_CH1="spi10.MCP3002@0.1"

# - Button (not soldered, open input, must not use it!)
BUTTON_PIN="missing"
# - LEDs
GREENLED_PIN="led.p44:green:status1"
REDLED_PIN="led.p44:red:status2"

# general settings
JSONAPIPORT=8090
FEATUREAPIPORT=11200
LOGLEVEL=6


# Allow overriding options (such as LOGLEVEL or EXTRAOPTS)
# - override from flash
if [ -f "/flash/${DAEMON}_cfg" ]; then
  source "/flash/${DAEMON}_cfg"
fi
# - override from tmp
if [ -f "/tmp/${DAEMON}_cfg" ]; then
  source "/tmp/${DAEMON}_cfg"
fi


# LED chains
# - we need PWM1 on GPIO45/46
omega2-ctrl gpiomux set uart1 pwm01
# - we need pwm2 and 3 as well
omega2-ctrl gpiomux set uart2 pwm23
# load driver (in variable mode, LED type/layout determined by app)
insmod p44-ledchain ${LEDCHAIN_NAME_1}=0,${MAX_LEDS},255 ${LEDCHAIN_NAME_2}=0,${MAX_LEDS},255 ${LEDCHAIN_NAME_3}=0,${MAX_LEDS},255


# PWM for LED dimmer: pwm0 on GPIO45
# - no config needed except pwm01 exposed, done for LED chain above already
#   (p44utils will export the pwm pin)

# SPI for MCP3002
# - we need the i2s pins for software SPI
omega2-ctrl gpiomux set i2s gpio
# - use software SPI (HW SPI does not work reliably on MT7688) for MCP3002
#   bus<Y>=<devid>,<SCK>,<MOSI>,<MISO>,<mode>,<speedInHz>,<CS>
#   Note: devid 0 (bus 0) is already in use by HW SPI, so we take 1
insmod spi-gpio-custom bus0=1,1,2,3,0,100000,0

#run
exec ${DAEMON} \
  --resourcepath /usr/share/leth \
  --datapath /flash \
  --pwmdimmer ${PWM_LED_FET_PIN} \
  ${LEDCHAINS} \
  --sensor0 ${ADC_INPUT_CH0} \
  --sensor1 ${ADC_INPUT_CH1} \
  ${WIFITRACK} \
  --initjson initcmds.json \
  --button ${BUTTON_PIN} \
  --greenled ${GREENLED_PIN} \
  --redled ${REDLED_PIN} \
  --jsonapiport ${JSONAPIPORT} \
  --jsonapinonlocal \
  --featureapiport ${FEATUREAPIPORT} \
  --ubusapi \
  ${APPCONFIG} \
  -l ${LOGLEVEL}
