# Run this script to install all packages that were installed at the time of p44b save
./scripts/feeds update onion
./scripts/feeds install -p onion gpio-test
./scripts/feeds install -p onion omega2-ctrl
./scripts/feeds install -p onion wifimanager
./scripts/feeds install -p onion wifisetup
./scripts/feeds update p44i
./scripts/feeds install -p p44i p44-maint-keys
./scripts/feeds update packages
./scripts/feeds install -p packages alsa-lib
./scripts/feeds install -p packages alsa-utils
#./scripts/feeds install -p packages alsa-utils-seq
#./scripts/feeds install -p packages alsa-utils-tests
./scripts/feeds install -p packages attr
#./scripts/feeds install -p packages libattr
./scripts/feeds install -p packages libavahi-client
#./scripts/feeds install -p packages libavahi-compat-libdnssd
#./scripts/feeds install -p packages avahi-utils
#./scripts/feeds install -p packages libavahi-dbus-support
#./scripts/feeds install -p packages libavahi-nodbus-support
#./scripts/feeds install -p packages avahi-autoipd
#./scripts/feeds install -p packages avahi-dbus-daemon
#./scripts/feeds install -p packages avahi-nodbus-daemon
#./scripts/feeds install -p packages avahi-daemon-service-http
#./scripts/feeds install -p packages avahi-daemon-service-ssh
#./scripts/feeds install -p packages avahi-dnsconfd
./scripts/feeds install -p packages bash
./scripts/feeds install -p packages bluez-examples
#./scripts/feeds install -p packages bluez-libs
#./scripts/feeds install -p packages bluez-utils
#./scripts/feeds install -p packages bluez-daemon
./scripts/feeds install -p packages boost-atomic
#./scripts/feeds install -p packages boost-chrono
#./scripts/feeds install -p packages boost-container
#./scripts/feeds install -p packages boost-context
#./scripts/feeds install -p packages boost-coroutine
#./scripts/feeds install -p packages boost-date_time
#./scripts/feeds install -p packages boost-fiber
#./scripts/feeds install -p packages boost-filesystem
#./scripts/feeds install -p packages boost-graph
#./scripts/feeds install -p packages boost-iostreams
#./scripts/feeds install -p packages boost-locale
#./scripts/feeds install -p packages boost-log
#./scripts/feeds install -p packages boost-math
#./scripts/feeds install -p packages boost-program_options
#./scripts/feeds install -p packages boost-python
#./scripts/feeds install -p packages boost-python3
#./scripts/feeds install -p packages boost-random
#./scripts/feeds install -p packages boost-regex
#./scripts/feeds install -p packages boost-serialization
#./scripts/feeds install -p packages boost-wserialization
#./scripts/feeds install -p packages boost-signals
#./scripts/feeds install -p packages boost-stacktrace
#./scripts/feeds install -p packages boost-system
#./scripts/feeds install -p packages boost-thread
#./scripts/feeds install -p packages boost-timer
#./scripts/feeds install -p packages boost-type_erasure
#./scripts/feeds install -p packages boost-wave
#./scripts/feeds install -p packages boost-test
#./scripts/feeds install -p packages boost-libs
#./scripts/feeds install -p packages boost
./scripts/feeds install -p packages libdb47
#./scripts/feeds install -p packages libdb47xx
./scripts/feeds install -p packages libdbus
#./scripts/feeds install -p packages dbus
#./scripts/feeds install -p packages dbus-utils
./scripts/feeds install -p packages libexpat
./scripts/feeds install -p packages libgdbm
./scripts/feeds install -p packages glib2
./scripts/feeds install -p packages intltool
./scripts/feeds install -p packages libdaemon
./scripts/feeds install -p packages libffi
./scripts/feeds install -p packages libical
./scripts/feeds install -p packages libpam
./scripts/feeds install -p packages libxml2
./scripts/feeds install -p packages openssh-client
#./scripts/feeds install -p packages openssh-moduli
#./scripts/feeds install -p packages openssh-client-utils
#./scripts/feeds install -p packages openssh-keygen
#./scripts/feeds install -p packages openssh-server
#./scripts/feeds install -p packages openssh-server-pam
#./scripts/feeds install -p packages openssh-sftp-client
#./scripts/feeds install -p packages openssh-sftp-server
#./scripts/feeds install -p packages openssh-sftp-avahi-service
./scripts/feeds install -p packages libprotobuf-c
./scripts/feeds install -p packages python-pip-conf
./scripts/feeds install -p packages libsqlite3
#./scripts/feeds install -p packages sqlite3-cli
./scripts/feeds install -p packages xz-utils
#./scripts/feeds install -p packages liblzma
#./scripts/feeds install -p packages lzmadec
#./scripts/feeds install -p packages lzmainfo
#./scripts/feeds install -p packages xz
#./scripts/feeds install -p packages xzdec
#./scripts/feeds install -p packages xzdiff
#./scripts/feeds install -p packages xzgrep
#./scripts/feeds install -p packages xzless
#./scripts/feeds install -p packages xzmore
./scripts/feeds update plan44
./scripts/feeds install -p plan44 hxcmodplayer
./scripts/feeds install -p plan44 i2c-tools
./scripts/feeds install -p plan44 libev
./scripts/feeds install -p plan44 libpng
./scripts/feeds install -p plan44 messagetorch
./scripts/feeds install -p plan44 mg44
./scripts/feeds install -p plan44 kmod-p44-ledchain
./scripts/feeds install -p plan44 p44sbbd
./scripts/feeds install -p plan44 p44wiper-config
./scripts/feeds install -p plan44 p44wiperd
./scripts/feeds install -p plan44 pagekitec
#./scripts/feeds install -p plan44 libpagekite
./scripts/feeds install -p plan44 pixelboard-config
./scripts/feeds install -p plan44 pixelboardd
./scripts/feeds install -p plan44 timidity
