#!/bin/sh

do_apply_dt_overlays() {
	grep -q configfs /proc/filesystems || return 0
	mount configfs -t configfs /sys/kernel/config
	local overlays_dir="/sys/kernel/config/device-tree/overlays"
	[ -d "$overlays_dir" ] || return 0
	local dto dtoname
	for dto in /lib/firmware/device-tree/overlays/*.dtbo ; do
		[ -r "$dto" ] || continue
		dtoname="$(basename "$dto" .dtbo)"
		[ -e "$overlays_dir/$dtoname" ] && continue
		if [ -e $overlays_dir/$dtoname ]; then
			echo " - device-tree overlay '$dtoname' already exists, not applying"
		else
			echo " - applying device-tree overlay '$dtoname'"
			mkdir "$overlays_dir/$dtoname"
			cat "$dto" >"$overlays_dir/$dtoname/dtbo"
		fi
		# dbbocfg does not enable the overlay automatically, need to write 1 to status
		echo " - enabling device-tree overlay '$dtoname' now"
		echo 1 > "$overlays_dir/$dtoname/status"
	done
}

boot_hook_add preinit_main do_apply_dt_overlays
