# FIXME: this is a ugly hack because for some reason Ethernet 1..4 pins get enabled, so we must disable them again
# see page 59 of MT7688 datasheet:
# - 1000003C is AGPIO_CFG register
# - 00E001FF is found there after startup
# - we write 00FE01FF to set bits 17..20 (but NOT bit 16, which is eth0!)
devmem 0x1000003C 32 >/tmp/AGPIO_original.txt
devmem 0x1000003C 32 0x001E01FF
# - LED_DATA0,1 on GPIO45/46 (UART1)
omega2-ctrl gpiomux set uart1 pwm01 2>/dev/null
