#!/bin/sh

DAEMON=p44featured

# app config
APPCONFIG="--mainscript simpleclock.txt"

# basic config Omega1 on controlboard v1/v2
# RS485TXOFFDELAY=2
# RS485PORT=/dev/ttyATH0
# RS485TXENPIN=gpio.26
# RS485RXENPIN=/gpio.23

# basic config Omega2 on splitflapcontroller v1
RS485TXOFFDELAY=3
RS485PORT=/dev/ttyS1
RS485TXENPIN=gpio.2
RS485RXENPIN=missing

# general settings
JSONAPIPORT=8090
STATEDIR=/tmp/p44sbbd
LOGLEVEL=5


# Allow overriding options (such as LOGLEVEL or EXTRAOPTS)
# - override from flash
if [ -f "/flash/${DAEMON}_cfg" ]; then
  source "/flash/${DAEMON}_cfg"
fi
# - override from tmp
if [ -f "/tmp/${DAEMON}_cfg" ]; then
  source "/tmp/${DAEMON}_cfg"
fi

# make the state dir
mkdir -p ${STATEDIR}
chmod 777 ${STATEDIR}

# prepare output
omega2-ctrl gpiomux set uart1 uart
omega2-ctrl gpiomux set i2s gpio
omega2-ctrl gpiomux set spi_s pwm01_uart2

#run
exec ${DAEMON} \
  --splitflapconn ${RS485PORT} \
  --splitflaptxoff ${RS485TXOFFDELAY} \
  --splitflaptxen ${RS485TXENPIN} \
  --splitflaprxen ${RS485RXENPIN} \
  --jsonapiport ${JSONAPIPORT} \
  --featureapiport 11200 \
  ${APPCONFIG} \
  -l ${LOGLEVEL}
