# Run this script to install all packages that were installed at the time of p44b save
./scripts/feeds update onion
./scripts/feeds install -p onion kmod-gpio-irq
./scripts/feeds install -p onion gpio-test
./scripts/feeds install -p onion omega2-ctrl
./scripts/feeds install -p onion wifimanager
./scripts/feeds install -p onion wifisetup
./scripts/feeds update raspberry
./scripts/feeds install -p raspberry weston
#./scripts/feeds install -p raspberry automake
#./scripts/feeds install -p raspberry m4
#./scripts/feeds install -p raspberry opengalax
#./scripts/feeds install -p raspberry kmod-uinput
#./scripts/feeds install -p raspberry cairo
#./scripts/feeds install -p raspberry libX11
#./scripts/feeds install -p raspberry libXcursor
#./scripts/feeds install -p raspberry libXfixes
#./scripts/feeds install -p raspberry libbullet
#./scripts/feeds install -p raspberry libevdev
#./scripts/feeds install -p raspberry libmpc
#./scripts/feeds install -p raspberry libpthread-stubs
#./scripts/feeds install -p raspberry libwayland
#./scripts/feeds install -p raspberry libxkbcommon
#./scripts/feeds install -p raspberry pixman
#./scripts/feeds install -p raspberry tslib
#./scripts/feeds install -p raspberry fixesproto
#./scripts/feeds install -p raspberry kbproto
#./scripts/feeds install -p raspberry xcbproto
#./scripts/feeds install -p raspberry xproto
#./scripts/feeds install -p raspberry fontconfig
#./scripts/feeds install -p raspberry rpi-extendfs
#./scripts/feeds install -p raspberry xkeyboard-config
./scripts/feeds update p44i
./scripts/feeds install -p p44i alix-flashbox-config
./scripts/feeds install -p p44i ds-vdc
./scripts/feeds install -p p44i mg44
./scripts/feeds install -p p44i p44-extdev-cecbutton
./scripts/feeds install -p p44i p44-extdev-htscreen
./scripts/feeds install -p p44i p44-maint-keys
./scripts/feeds install -p p44i kmod-p44dbr
./scripts/feeds install -p p44i p44dsb-config
./scripts/feeds install -p p44i p44dsb-webui
./scripts/feeds install -p p44i p44lc-config
./scripts/feeds install -p p44i p44lc-webui
./scripts/feeds install -p p44i p44maintd
./scripts/feeds install -p p44i p44pagekite
./scripts/feeds install -p p44i serialfwd
./scripts/feeds install -p p44i sqfloatswapper
./scripts/feeds install -p p44i vdcd
./scripts/feeds install -p p44i vdsm
./scripts/feeds update packages
./scripts/feeds install -p packages alsa-lib
./scripts/feeds install -p packages alsa-utils
#./scripts/feeds install -p packages alsa-utils-seq
#./scripts/feeds install -p packages alsa-utils-tests
./scripts/feeds install -p packages libavahi-client
#./scripts/feeds install -p packages libavahi-compat-libdnssd
#./scripts/feeds install -p packages avahi-utils
#./scripts/feeds install -p packages libavahi-dbus-support
#./scripts/feeds install -p packages libavahi-nodbus-support
#./scripts/feeds install -p packages avahi-autoipd
#./scripts/feeds install -p packages avahi-dbus-daemon
#./scripts/feeds install -p packages avahi-nodbus-daemon
#./scripts/feeds install -p packages avahi-daemon-service-http
#./scripts/feeds install -p packages avahi-daemon-service-ssh
#./scripts/feeds install -p packages avahi-dnsconfd
./scripts/feeds install -p packages bash
./scripts/feeds install -p packages boost-atomic
#./scripts/feeds install -p packages boost-chrono
#./scripts/feeds install -p packages boost-container
#./scripts/feeds install -p packages boost-context
#./scripts/feeds install -p packages boost-coroutine
#./scripts/feeds install -p packages boost-date_time
#./scripts/feeds install -p packages boost-fiber
#./scripts/feeds install -p packages boost-filesystem
#./scripts/feeds install -p packages boost-graph
#./scripts/feeds install -p packages boost-iostreams
#./scripts/feeds install -p packages boost-locale
#./scripts/feeds install -p packages boost-log
#./scripts/feeds install -p packages boost-math
#./scripts/feeds install -p packages boost-program_options
#./scripts/feeds install -p packages boost-python
#./scripts/feeds install -p packages boost-python3
#./scripts/feeds install -p packages boost-random
#./scripts/feeds install -p packages boost-regex
#./scripts/feeds install -p packages boost-serialization
#./scripts/feeds install -p packages boost-signals
#./scripts/feeds install -p packages boost-system
#./scripts/feeds install -p packages boost-thread
#./scripts/feeds install -p packages boost-timer
#./scripts/feeds install -p packages boost-wave
#./scripts/feeds install -p packages boost-test
#./scripts/feeds install -p packages boost-libs
#./scripts/feeds install -p packages boost
./scripts/feeds install -p packages libsasl2
./scripts/feeds install -p packages libdb47
#./scripts/feeds install -p packages libdb47xx
./scripts/feeds install -p packages libdbus
#./scripts/feeds install -p packages dbus
#./scripts/feeds install -p packages dbus-utils
./scripts/feeds install -p packages libexpat
./scripts/feeds install -p packages libfreetype
./scripts/feeds install -p packages libgdbm
./scripts/feeds install -p packages icu
./scripts/feeds install -p packages intltool
./scripts/feeds install -p packages libdaemon
./scripts/feeds install -p packages libffi
./scripts/feeds install -p packages libjpeg
#./scripts/feeds install -p packages jpeg-tools
./scripts/feeds install -p packages liblo
#./scripts/feeds install -p packages liblo-utils
./scripts/feeds install -p packages libmcrypt
./scripts/feeds install -p packages libpam
./scripts/feeds install -p packages libxml2
./scripts/feeds install -p packages mysql-server
#./scripts/feeds install -p packages libmysqlclient
#./scripts/feeds install -p packages libmysqlclient-r
./scripts/feeds install -p packages netdata
./scripts/feeds install -p packages ola
./scripts/feeds install -p packages libopenldap
#./scripts/feeds install -p packages openldap-utils
#./scripts/feeds install -p packages openldap-server
./scripts/feeds install -p packages openssh-client
#./scripts/feeds install -p packages openssh-moduli
#./scripts/feeds install -p packages openssh-client-utils
#./scripts/feeds install -p packages openssh-keygen
#./scripts/feeds install -p packages openssh-server
#./scripts/feeds install -p packages openssh-server-pam
#./scripts/feeds install -p packages openssh-sftp-client
#./scripts/feeds install -p packages openssh-sftp-server
#./scripts/feeds install -p packages openssh-sftp-avahi-service
./scripts/feeds install -p packages libpcre
#./scripts/feeds install -p packages libpcre16
#./scripts/feeds install -p packages libpcrecpp
./scripts/feeds install -p packages php7
#./scripts/feeds install -p packages php7-cgi
#./scripts/feeds install -p packages php7-cli
#./scripts/feeds install -p packages php7-fastcgi
#./scripts/feeds install -p packages php7-fpm
#./scripts/feeds install -p packages php7-mod-calendar
#./scripts/feeds install -p packages php7-mod-ctype
#./scripts/feeds install -p packages php7-mod-curl
#./scripts/feeds install -p packages php7-mod-dom
#./scripts/feeds install -p packages php7-mod-exif
#./scripts/feeds install -p packages php7-mod-fileinfo
#./scripts/feeds install -p packages php7-mod-ftp
#./scripts/feeds install -p packages php7-mod-gd
#./scripts/feeds install -p packages php7-mod-gettext
#./scripts/feeds install -p packages php7-mod-gmp
#./scripts/feeds install -p packages php7-mod-hash
#./scripts/feeds install -p packages php7-mod-iconv
#./scripts/feeds install -p packages php7-mod-intl
#./scripts/feeds install -p packages php7-mod-json
#./scripts/feeds install -p packages php7-mod-ldap
#./scripts/feeds install -p packages php7-mod-mbstring
#./scripts/feeds install -p packages php7-mod-mcrypt
#./scripts/feeds install -p packages php7-mod-mysqli
#./scripts/feeds install -p packages php7-mod-opcache
#./scripts/feeds install -p packages php7-mod-openssl
#./scripts/feeds install -p packages php7-mod-pcntl
#./scripts/feeds install -p packages php7-mod-pdo
#./scripts/feeds install -p packages php7-mod-pdo-mysql
#./scripts/feeds install -p packages php7-mod-pdo-pgsql
#./scripts/feeds install -p packages php7-mod-pdo-sqlite
#./scripts/feeds install -p packages php7-mod-pgsql
#./scripts/feeds install -p packages php7-mod-phar
#./scripts/feeds install -p packages php7-mod-session
#./scripts/feeds install -p packages php7-mod-shmop
#./scripts/feeds install -p packages php7-mod-simplexml
#./scripts/feeds install -p packages php7-mod-soap
#./scripts/feeds install -p packages php7-mod-sockets
#./scripts/feeds install -p packages php7-mod-sqlite3
#./scripts/feeds install -p packages php7-mod-sysvmsg
#./scripts/feeds install -p packages php7-mod-sysvsem
#./scripts/feeds install -p packages php7-mod-sysvshm
#./scripts/feeds install -p packages php7-mod-tokenizer
#./scripts/feeds install -p packages php7-mod-xml
#./scripts/feeds install -p packages php7-mod-xmlreader
#./scripts/feeds install -p packages php7-mod-xmlwriter
#./scripts/feeds install -p packages php7-mod-zip
./scripts/feeds install -p packages libpq
#./scripts/feeds install -p packages pgsql-cli
#./scripts/feeds install -p packages pgsql-cli-extra
#./scripts/feeds install -p packages pgsql-server
./scripts/feeds install -p packages protobuf
./scripts/feeds install -p packages libprotobuf-c
./scripts/feeds install -p packages librrd1
#./scripts/feeds install -p packages rrdcgi1
#./scripts/feeds install -p packages rrdtool1
./scripts/feeds install -p packages libsqlite3
#./scripts/feeds install -p packages sqlite3-cli
./scripts/feeds install -p packages sudo
./scripts/feeds install -p packages tinc
./scripts/feeds install -p packages xz-utils
#./scripts/feeds install -p packages liblzma
#./scripts/feeds install -p packages lzmadec
#./scripts/feeds install -p packages lzmainfo
#./scripts/feeds install -p packages xz
#./scripts/feeds install -p packages xzdec
#./scripts/feeds install -p packages xzdiff
#./scripts/feeds install -p packages xzgrep
#./scripts/feeds install -p packages xzless
#./scripts/feeds install -p packages xzmore
./scripts/feeds update plan44
./scripts/feeds install -p plan44 i2c-tools
./scripts/feeds install -p plan44 leth-config
./scripts/feeds install -p plan44 lethd
./scripts/feeds install -p plan44 libev
./scripts/feeds install -p plan44 libpng
./scripts/feeds install -p plan44 lora_gateway
./scripts/feeds install -p plan44 messagetorch
./scripts/feeds install -p plan44 p44-extdev-elsner
./scripts/feeds install -p plan44 kmod-p44-ledchain
./scripts/feeds install -p plan44 p44ayabd
./scripts/feeds install -p plan44 p44bandit-config
./scripts/feeds install -p plan44 p44banditd
./scripts/feeds install -p plan44 p44sbb-config
./scripts/feeds install -p plan44 p44sbbd
./scripts/feeds install -p plan44 p44ttngw-config
./scripts/feeds install -p plan44 p44wiper-config
./scripts/feeds install -p plan44 p44wiperd
./scripts/feeds install -p plan44 packet_forwarder
./scripts/feeds install -p plan44 pagekitec
#./scripts/feeds install -p plan44 libpagekite
./scripts/feeds install -p plan44 pixelboard-config
./scripts/feeds install -p plan44 pixelboardd
./scripts/feeds install -p plan44 kmod-rcswitch
./scripts/feeds install -p plan44 rpi-userland
#./scripts/feeds install -p plan44 rpi-vcgencmd
#./scripts/feeds install -p plan44 rpi-raspicam
#./scripts/feeds install -p plan44 rpi-tvservice
#./scripts/feeds install -p plan44 rpi-helloaudio
#./scripts/feeds install -p plan44 rpi-hellodispmanx
#./scripts/feeds install -p plan44 rpi-helloencode
#./scripts/feeds install -p plan44 rpi-hellofont
#./scripts/feeds install -p plan44 rpi-hellojpeg
#./scripts/feeds install -p plan44 rpi-helloteapot
#./scripts/feeds install -p plan44 rpi-hellotiger
#./scripts/feeds install -p plan44 rpi-hellotriangle
#./scripts/feeds install -p plan44 rpi-hellotriangle2
#./scripts/feeds install -p plan44 rpi-hellovideo
#./scripts/feeds install -p plan44 rpi-hellovideocube
#./scripts/feeds install -p plan44 rpi-helloworld
./scripts/feeds install -p plan44 sshpass
./scripts/feeds install -p plan44 timidity
./scripts/feeds install -p plan44 kmod-ws2812-draiveris
./scripts/feeds update stintel
./scripts/feeds install -p stintel libcec
./scripts/feeds install -p stintel libp8-platform
./scripts/feeds install -p stintel raspberrypi-userland
