#!/bin/sh

# default features
EXECUTABLE=p44banditd
LOGLEVEL=6
EXTRAOPTS=

# config
DATADIR="/flash/datadir"

# basic config Omega2 on serialcontroller v1
SERIALPORT=/dev/ttyS1
HSOUTPIN=/gpio.39
HSINPIN=/gpio.40

# - Button
BUTTON_PIN=gpio.38
# - LEDs
GREENLED_PIN="led.p44:green:status1"
REDLED_PIN="led.p44:red:status2"


# prepare
mkdir -p ${DATADIR}


# run the daemon
exec ${EXECUTABLE} \
  --jsonapiport 8090 \
  --serialport ${SERIALPORT} \
  --hsoutpin ${HSOUTPIN} \
  --hsinpin ${HSINPIN} \
  --button ${BUTTON_PIN} \
  --greenled ${GREENLED_PIN} \
  --redled ${REDLED_PIN} \
  --datapath ${DATADIR}
  -l ${LOGLEVEL} \
  ${EXTRAOPTS} \
  </dev/null
