#!/bin/sh

# default features
EXECUTABLE=p44banditd
LOGLEVEL=6
EXTRAOPTS=

# config
DATADIR="/flash/datadir"

# basic config Omega2 on serialcontroller v1
SERIALPORT=/dev/ttyS1
HSOUTPIN=/gpio.39
HSINPIN=/gpio.40

# prepare
mkdir -p ${DATADIR}


# run the daemon
exec ${EXECUTABLE} \
  --jsonapiport 8090 \
  --serialport ${SERIALPORT} \
  --hsoutpin ${HSOUTPIN} \
  --hsinpin ${HSINPIN} \
  --datadir ${DATADIR}
  -l ${LOGLEVEL} \
  ${EXTRAOPTS} \
  </dev/null
