#!/bin/sh

# default features
EXECUTABLE=pixelboardd
LOGLEVEL=5
EXTRAOPTS=
MESSAGE=

# platform params (Omega2, v3 board)
PLATFORM_LEDCHAIN_DEVICE="/dev/ledchain0"
PLATFORM_LEDCHAIN_NUMLEDS="200"

# Allow overriding options
# - override from flash
if [ -e /flash/pixelboardd_debug ]; then
  source /flash/pixelboardd_debug
fi
# - override from tmp
if [ -e /tmp/pixelboardd_debug ]; then
  source /tmp/pixelboardd_debug
fi

# load the LED chain kernel module
# - Omega2 with non-inverted WS2813 LEDs (must switch GPIO18/19 to GPIO mode first via devmem)!
devmem 0x1000003C 32 0x00FE01FF
omega2-ctrl gpiomux set pwm0 pwm
insmod p44-ledchain ledchain0=0,${PLATFORM_LEDCHAIN_NUMLEDS},2

# configure GPIOs for i2c switch, reset, change sense for touch boards
# - use a software i2c because the hardware bus is too fast for the long wires
omega2-ctrl gpiomux set i2c gpio
insmod i2c-gpio-custom bus1=1,5,4,50,10,0,0,1

# GPIO6 is SPI_CS1 by default, switch to GPIO
omega2-ctrl gpiomux set spi_cs1 gpio
# GPIO6 = /TOUCH_RST (0=Reset, 1=run)
# GPIO0 = TOUCH_SEL (1=far end P4 touch board SCL enabled, 0=near end P3 touch board enabled)
# GPIO15 = /TOUCH_CHG (0=change detected)
echo 6 >/sys/class/gpio/export
echo 0 >/sys/class/gpio/export
echo 15 >/sys/class/gpio/export
# keep reset
echo out >/sys/class/gpio/gpio6/direction
echo 0 >/sys/class/gpio/gpio6/value
# side selector
echo out >/sys/class/gpio/gpio0/direction
# release reset
echo 1 >/sys/class/gpio/gpio6/value

for SIDE in 0 1; do
  # set side
  echo $SIDE >/sys/class/gpio/gpio0/value
  # configure key LEDs
  # - turn off LEDs (active LOW) - OLATA
  i2cset -y 1 0x20 0x14 0x1E
  # - make GPA1..4 outputs (clear bits in IODIRA)
  i2cset -y 1 0x20 0x00 0xE1
  # - turn LEDs on during calibration
  i2cset -y 1 0x20 0x14 0x00
  # configure touch
  # - disable keys 5 and 6 (Averaging factor 0)
  i2cset -y 1 0x1B 44 0
  i2cset -y 1 0x1B 45 0
  # - disable adjacent key group (Bits 0..2, by default, all keys are in group 1, 0=none)
  #   and set averaging factor (Bits 3..7, by default==8)
  i2cset -y 1 0x1B 39 0x40
  i2cset -y 1 0x1B 40 0x20
  i2cset -y 1 0x1B 41 0x20
  i2cset -y 1 0x1B 42 0x20
  i2cset -y 1 0x1B 43 0x20
  # - lower threshold, default = 20
  i2cset -y 1 0x1B 32 7
  i2cset -y 1 0x1B 33 10
  i2cset -y 1 0x1B 34 10
  i2cset -y 1 0x1B 35 10
  i2cset -y 1 0x1B 36 10
  # - integrators, default = 4
  i2cset -y 1 0x1B 46 2
  i2cset -y 1 0x1B 47 5
  i2cset -y 1 0x1B 48 5
  i2cset -y 1 0x1B 49 5
  i2cset -y 1 0x1B 50 5
  # disable guard channel
  # - averaging factor 0 = disabled
  i2cset -y 1 0x1B 39 0
  # - normally 0, 8=invalid guard channel=off
  i2cset -y 1 0x1B 53 8
  # recalibrate (with LEDs on)
  i2cset -y 1 0x1B 56 1
done

# run the daemon
exec ${EXECUTABLE} \
  --i2cbusno 1 \
  --ledchain "${PLATFORM_LEDCHAIN_DEVICE}" \
  --jsonapiport 8090 \
  --defaultpage display \
  --image /www/images/default.png \
  --message "${MESSAGE}" \
  -l ${LOGLEVEL} \
  ${EXTRAOPTS} \
  </dev/null
