#!/bin/sh

APPNAME=p44mctrld
KVSPATH=/flash/${APPNAME}_kvs

echo ""
echo "**************** ${APPNAME} exited with status $1, waitpid status $2 ********************"
ps -ww
echo ""

echo "[`date`] ${APPNAME} exited with exitstatus $1, waitpid status $2" >>/var/log/${APPNAME}/exits.log

if [ $1 == 42 ]; then
  # exit code 42 factory resets the matter controller
  echo "[`date`] ${APPNAME} requests factory reset" >>/var/log/${APPNAME}/exits.log
  # erase KVS config file
  rm "${KVSPATH}"
elif [ $1 == 0 ]; then
  # clean exit
  echo "clean exit"
else
# just to damp possible crashloops
  echo "error exit -> wait 3 seconds to damp loops"
  sleep 3
fi
