#!/bin/sh

DAEMON="kksdcmd"
LOGDIR="/var/log/${DAEMON}"

# check options
DUMP=0
DUMPALL=0
LOGLEVEL=0
BACKLOG=10
LOGCHANGE=0
for OPT in $@ ; do
  case "${OPT}" in
    "-d"|"--dump") DUMP=1;;
    "-a"|"--all") DUMPALL=1;;
    "-n"|"--new") BACKLOG=0;;
    "-l"|"--long") BACKLOG=$((${BACKLOG}+20));;
    *) if [ $(($OPT)) -ne 0 ]; then
         LOGLEVEL=$((${OPT})); LOGCHANGE=1;
       else
         if [ "${OPT}" != "-h" ]; then echo "unknown option $OPT"; fi;
         echo "Usage: $0 [options] [new loglevel]";
         echo "Options:";
         echo "  -d, --dump : show entire current log, do not wait for more log";
         echo "  -a, --all  : show all available logs, do not wait for more log";
         echo "  -n, --new  : wait for and show only new log lines (no backlog)";
         echo "  -l, --long : extend backlog (by 20 lines) and wait for new log lines";
         echo "               (can be used more than once)";
         return 1;
       fi
       ;;
  esac
done

if [ "${LOGCHANGE}" -eq "1" ]; then
  ubus call ${DAEMON} log "{ 'level': ${LOGLEVEL} }"
fi

if [ "${DUMPALL}" -ne "0" ]; then
  cd "${LOGDIR}"
  cat @*.s "current"
elif [ "${DUMP}" -ne "0" ]; then
  cat "${LOGDIR}/current"
else
  tail -F -n "$(($BACKLOG+$LOGCHANGE))" "${LOGDIR}/current"
fi
