# Run this script to install all packages that were installed at the time of p44b save
# Note: this script uses a fast installation method that does not detect package dependencies.
#   This is fine when the saved set is consistent and has resolved dependencies already.
#   Otherwise, use install_packages.sh insetad, which is slow but resolves dependencies.

# install packages from feed 'onion':
# - make sure feed is current
./scripts/feeds update onion
# - softlink (=install) package dirs
mkdir -p package/feeds/onion
pushd package/feeds/onion
ln -s ../../../feeds/onion/omega2-ctrl
popd
# - end of feed 'onion'

# install packages from feed 'matter':
# - make sure feed is current
./scripts/feeds update matter
# - softlink (=install) package dirs
mkdir -p package/feeds/matter
pushd package/feeds/matter
ln -s ../../../feeds/matter/devel/gn
popd
# - end of feed 'matter'

# install packages from feed 'packages':
# - make sure feed is current
./scripts/feeds update packages
# - softlink (=install) package dirs
mkdir -p package/feeds/packages
pushd package/feeds/packages
ln -s ../../../feeds/packages/net/acme
ln -s ../../../feeds/packages/net/aircrack-ng
ln -s ../../../feeds/packages/libs/alsa-lib
ln -s ../../../feeds/packages/libs/alsa-ucm-conf
ln -s ../../../feeds/packages/sound/alsa-utils
ln -s ../../../feeds/packages/net/apinger
ln -s ../../../feeds/packages/utils/apk
ln -s ../../../feeds/packages/utils/attendedsysupgrade-common
ln -s ../../../feeds/packages/utils/attr
ln -s ../../../feeds/packages/utils/auc
ln -s ../../../feeds/packages/utils/audit
ln -s ../../../feeds/packages/utils/augeas
ln -s ../../../feeds/packages/devel/autoconf
ln -s ../../../feeds/packages/devel/automake
ln -s ../../../feeds/packages/libs/avahi
ln -s ../../../feeds/packages/utils/bash
ln -s ../../../feeds/packages/utils/beep
ln -s ../../../feeds/packages/net/bind
ln -s ../../../feeds/packages/utils/bluez
ln -s ../../../feeds/packages/net/bonding
ln -s ../../../feeds/packages/libs/boost
ln -s ../../../feeds/packages/net/bridge-utils
ln -s ../../../feeds/packages/libs/c-ares
ln -s ../../../feeds/packages/utils/canutils
ln -s ../../../feeds/packages/utils/ccrypt
ln -s ../../../feeds/packages/net/cifs-utils
ln -s ../../../feeds/packages/libs/cjson
ln -s ../../../feeds/packages/libs/confuse
ln -s ../../../feeds/packages/net/daemonlogger
ln -s ../../../feeds/packages/libs/db47
ln -s ../../../feeds/packages/utils/dbus
ln -s ../../../feeds/packages/admin/debian-archive-keyring
ln -s ../../../feeds/packages/net/dhcp-forwarder
ln -s ../../../feeds/packages/net/dhcpcd
ln -s ../../../feeds/packages/devel/diffutils
ln -s ../../../feeds/packages/libs/dmx_usb_module
ln -s ../../../feeds/packages/utils/ecdsautils
ln -s ../../../feeds/packages/net/etherwake
ln -s ../../../feeds/packages/libs/expat
ln -s ../../../feeds/packages/libs/file
ln -s ../../../feeds/packages/utils/findutils
ln -s ../../../feeds/packages/libs/flac
ln -s ../../../feeds/packages/net/fping
ln -s ../../../feeds/packages/net/gatling
ln -s ../../../feeds/packages/utils/gawk
ln -s ../../../feeds/packages/devel/gcc
ln -s ../../../feeds/packages/libs/gdbm
ln -s ../../../feeds/packages/utils/gddrescue
ln -s ../../../feeds/packages/ipv6/generate-ipv6-address
ln -s ../../../feeds/packages/libs/giflib
ln -s ../../../feeds/packages/libs/glib2
ln -s ../../../feeds/packages/libs/gnutls
ln -s ../../../feeds/packages/utils/grep
ln -s ../../../feeds/packages/utils/gzip
ln -s ../../../feeds/packages/utils/hfsprogs
ln -s ../../../feeds/packages/utils/hwdata
ln -s ../../../feeds/packages/utils/hwinfo
ln -s ../../../feeds/packages/libs/hwloc
ln -s ../../../feeds/packages/utils/i2c-tools
ln -s ../../../feeds/packages/net/i2pd
ln -s ../../../feeds/packages/net/ifstat
ln -s ../../../feeds/packages/net/iftop
ln -s ../../../feeds/packages/net/igmpproxy
ln -s ../../../feeds/packages/net/iperf
ln -s ../../../feeds/packages/net/iperf3
ln -s ../../../feeds/packages/net/iputils
ln -s ../../../feeds/packages/libs/jsoncpp
ln -s ../../../feeds/packages/libs/keyutils
ln -s ../../../feeds/packages/utils/kitty-terminfo
ln -s ../../../feeds/packages/utils/kmod
ln -s ../../../feeds/packages/utils/less
ln -s ../../../feeds/packages/libs/libarchive
ln -s ../../../feeds/packages/libs/libcap-ng
ln -s ../../../feeds/packages/libs/libcbor
ln -s ../../../feeds/packages/libs/libcgroup
ln -s ../../../feeds/packages/libs/libconfig
ln -s ../../../feeds/packages/libs/libdaemon
ln -s ../../../feeds/packages/libs/libdaq
ln -s ../../../feeds/packages/libs/libdaq3
ln -s ../../../feeds/packages/libs/libdbi
ln -s ../../../feeds/packages/libs/libdcwproto
ln -s ../../../feeds/packages/libs/libdcwsocket
ln -s ../../../feeds/packages/libs/libdnet
ln -s ../../../feeds/packages/libs/libdrm
ln -s ../../../feeds/packages/libs/libdvbcsa
ln -s ../../../feeds/packages/libs/libebml
ln -s ../../../feeds/packages/libs/libedit
ln -s ../../../feeds/packages/libs/libesmtp
ln -s ../../../feeds/packages/libs/libestr
ln -s ../../../feeds/packages/libs/libev
ln -s ../../../feeds/packages/libs/libevdev
ln -s ../../../feeds/packages/libs/libexif
ln -s ../../../feeds/packages/libs/libfastjson
ln -s ../../../feeds/packages/libs/libffi
ln -s ../../../feeds/packages/libs/libfido2
ln -s ../../../feeds/packages/libs/libfmt
ln -s ../../../feeds/packages/libs/libfstrm
ln -s ../../../feeds/packages/libs/libftdi
ln -s ../../../feeds/packages/libs/libftdi1
ln -s ../../../feeds/packages/libs/libgcrypt
ln -s ../../../feeds/packages/libs/libgpg-error
ln -s ../../../feeds/packages/libs/libgphoto2
ln -s ../../../feeds/packages/libs/libgpiod
ln -s ../../../feeds/packages/libs/libhttp-parser
ln -s ../../../feeds/packages/libs/libical
ln -s ../../../feeds/packages/libs/libid3tag
ln -s ../../../feeds/packages/libs/libidn
ln -s ../../../feeds/packages/libs/libidn2
ln -s ../../../feeds/packages/libs/libiio
ln -s ../../../feeds/packages/libs/libimobiledevice
ln -s ../../../feeds/packages/libs/libinput
ln -s ../../../feeds/packages/libs/libirecovery
ln -s ../../../feeds/packages/libs/libjpeg-turbo
ln -s ../../../feeds/packages/libs/libksba
ln -s ../../../feeds/packages/libs/liblo
ln -s ../../../feeds/packages/libs/liblz4
ln -s ../../../feeds/packages/libs/libmad
ln -s ../../../feeds/packages/libs/libmatroska
ln -s ../../../feeds/packages/libs/libmaxminddb
ln -s ../../../feeds/packages/libs/libmcrypt
ln -s ../../../feeds/packages/libs/libmicrohttpd
ln -s ../../../feeds/packages/libs/libmms
ln -s ../../../feeds/packages/libs/libmodbus
ln -s ../../../feeds/packages/libs/libmpdclient
ln -s ../../../feeds/packages/libs/libmpeg2
ln -s ../../../feeds/packages/libs/libnatpmp
ln -s ../../../feeds/packages/net/libndp
ln -s ../../../feeds/packages/libs/libndpi
ln -s ../../../feeds/packages/libs/libnet-1.2.x
ln -s ../../../feeds/packages/libs/libnetconf2
ln -s ../../../feeds/packages/libs/libnetfilter-acct
ln -s ../../../feeds/packages/libs/libnetfilter-cthelper
ln -s ../../../feeds/packages/libs/libnetfilter-cttimeout
ln -s ../../../feeds/packages/libs/libnetfilter-log
ln -s ../../../feeds/packages/libs/libnetfilter-queue
ln -s ../../../feeds/packages/libs/libnopoll
ln -s ../../../feeds/packages/libs/libogg
ln -s ../../../feeds/packages/libs/liboil
ln -s ../../../feeds/packages/libs/liboping
ln -s ../../../feeds/packages/libs/libopusenc
ln -s ../../../feeds/packages/libs/liborcania
ln -s ../../../feeds/packages/libs/libowfat
ln -s ../../../feeds/packages/libs/libp11
ln -s ../../../feeds/packages/libs/libpam
ln -s ../../../feeds/packages/libs/libpbc
ln -s ../../../feeds/packages/libs/libpciaccess
ln -s ../../../feeds/packages/libs/libpfring
ln -s ../../../feeds/packages/libs/libplist
ln -s ../../../feeds/packages/libs/libpng
ln -s ../../../feeds/packages/libs/libpqxx
ln -s ../../../feeds/packages/libs/libpsl
ln -s ../../../feeds/packages/libs/libradiotap
ln -s ../../../feeds/packages/libs/libre2
ln -s ../../../feeds/packages/libs/libredblack
ln -s ../../../feeds/packages/libs/librouteros
ln -s ../../../feeds/packages/libs/libroxml
ln -s ../../../feeds/packages/libs/libsamplerate
ln -s ../../../feeds/packages/libs/libshout
ln -s ../../../feeds/packages/libs/libsndfile
ln -s ../../../feeds/packages/libs/libsoc
ln -s ../../../feeds/packages/libs/libsodium
ln -s ../../../feeds/packages/libs/libsoxr
ln -s ../../../feeds/packages/libs/libssh
ln -s ../../../feeds/packages/libs/libssh2
ln -s ../../../feeds/packages/libs/libstrophe
ln -s ../../../feeds/packages/libs/libtasn1
ln -s ../../../feeds/packages/libs/libtheora
ln -s ../../../feeds/packages/libs/libtins
ln -s ../../../feeds/packages/libs/libtirpc
ln -s ../../../feeds/packages/devel/libtool-bin
ln -s ../../../feeds/packages/libs/libtorrent
ln -s ../../../feeds/packages/libs/libtorrent-rasterbar
ln -s ../../../feeds/packages/libs/libudev-zero
ln -s ../../../feeds/packages/libs/libuecc
ln -s ../../../feeds/packages/libs/libugpio
ln -s ../../../feeds/packages/libs/libuhttpd
ln -s ../../../feeds/packages/libs/libunistring
ln -s ../../../feeds/packages/libs/libupnp
ln -s ../../../feeds/packages/libs/liburcu
ln -s ../../../feeds/packages/libs/liburing
ln -s ../../../feeds/packages/libs/libusb-compat
ln -s ../../../feeds/packages/libs/libusbmuxd
ln -s ../../../feeds/packages/libs/libuv
ln -s ../../../feeds/packages/libs/libuwifi
ln -s ../../../feeds/packages/libs/libuwsc
ln -s ../../../feeds/packages/libs/libv4l
ln -s ../../../feeds/packages/libs/libvorbis
ln -s ../../../feeds/packages/libs/libvorbisidec
ln -s ../../../feeds/packages/libs/libvpx
ln -s ../../../feeds/packages/libs/libwebp
ln -s ../../../feeds/packages/libs/libwebsockets
ln -s ../../../feeds/packages/libs/libwslay
ln -s ../../../feeds/packages/libs/libx264
ln -s ../../../feeds/packages/libs/libxcrypt
ln -s ../../../feeds/packages/libs/libxerces-c
ln -s ../../../feeds/packages/libs/libxml2
ln -s ../../../feeds/packages/libs/libxslt
ln -s ../../../feeds/packages/libs/libyaml-cpp
ln -s ../../../feeds/packages/libs/libyang
ln -s ../../../feeds/packages/libs/libyubikey
ln -s ../../../feeds/packages/net/lora-gateway-hal
ln -s ../../../feeds/packages/utils/lsof
ln -s ../../../feeds/packages/lang/lua-bencode
ln -s ../../../feeds/packages/lang/lua-cjson
ln -s ../../../feeds/packages/lang/lua-copas
ln -s ../../../feeds/packages/lang/lua-coxpcall
ln -s ../../../feeds/packages/lang/lua-ev
ln -s ../../../feeds/packages/lang/lua-libmodbus
ln -s ../../../feeds/packages/lang/lua-lsqlite3
ln -s ../../../feeds/packages/lang/lua-lzlib
ln -s ../../../feeds/packages/lang/lua-md5
ln -s ../../../feeds/packages/lang/lua-mobdebug
ln -s ../../../feeds/packages/lang/lua-openssl
ln -s ../../../feeds/packages/lang/lua-penlight
ln -s ../../../feeds/packages/lang/lua-rings
ln -s ../../../feeds/packages/lang/lua-rs232
ln -s ../../../feeds/packages/lang/lua-sha2
ln -s ../../../feeds/packages/lang/lua-wsapi
ln -s ../../../feeds/packages/lang/lua-xavante
ln -s ../../../feeds/packages/lang/luabitop
ln -s ../../../feeds/packages/lang/luaexpat
ln -s ../../../feeds/packages/lang/luafilesystem
ln -s ../../../feeds/packages/lang/luajit
ln -s ../../../feeds/packages/lang/lualanes
ln -s ../../../feeds/packages/lang/luaossl
ln -s ../../../feeds/packages/lang/luasec
ln -s ../../../feeds/packages/lang/luasoap
ln -s ../../../feeds/packages/lang/luasocket
ln -s ../../../feeds/packages/lang/luasrcdiet
ln -s ../../../feeds/packages/lang/luv
ln -s ../../../feeds/packages/net/lynx
ln -s ../../../feeds/packages/lang/lzmq
ln -s ../../../feeds/packages/libs/lzo
ln -s ../../../feeds/packages/devel/m4
ln -s ../../../feeds/packages/net/mac-telnet
ln -s ../../../feeds/packages/net/maccalc
ln -s ../../../feeds/packages/utils/macchanger
ln -s ../../../feeds/packages/kernel/macremapper
ln -s ../../../feeds/packages/sound/madplay
ln -s ../../../feeds/packages/mail/mailsend
ln -s ../../../feeds/packages/devel/make
ln -s ../../../feeds/packages/utils/mandoc
ln -s ../../../feeds/packages/mail/mblaze
ln -s ../../../feeds/packages/net/mbusd
ln -s ../../../feeds/packages/kernel/mdio-netlink
ln -s ../../../feeds/packages/net/mdio-tools
ln -s ../../../feeds/packages/net/mdns-repeater
ln -s ../../../feeds/packages/net/mdnsresponder
ln -s ../../../feeds/packages/net/memcached
ln -s ../../../feeds/packages/utils/mg
ln -s ../../../feeds/packages/utils/micrond
ln -s ../../../feeds/packages/lang/python/micropython
ln -s ../../../feeds/packages/lang/python/micropython-lib
ln -s ../../../feeds/packages/net/mikrotik-btest
ln -s ../../../feeds/packages/net/mini_snmpd
ln -s ../../../feeds/packages/utils/minicom
ln -s ../../../feeds/packages/multimedia/minisatip
ln -s ../../../feeds/packages/net/miniupnpc
ln -s ../../../feeds/packages/net/miniupnpd
ln -s ../../../feeds/packages/libs/minizip
ln -s ../../../feeds/packages/ipv6/miredo
ln -s ../../../feeds/packages/multimedia/mjpg-streamer
ln -s ../../../feeds/packages/utils/mksh
ln -s ../../../feeds/packages/utils/mktorrent
ln -s ../../../feeds/packages/utils/mmc-utils
ln -s ../../../feeds/packages/admin/monit
ln -s ../../../feeds/packages/utils/moreutils
ln -s ../../../feeds/packages/net/mosh
ln -s ../../../feeds/packages/net/mosquitto
ln -s ../../../feeds/packages/utils/mpack
ln -s ../../../feeds/packages/sound/mpc
ln -s ../../../feeds/packages/sound/mpg123
ln -s ../../../feeds/packages/net/mrmctl
ln -s ../../../feeds/packages/libs/msgpack-c
ln -s ../../../feeds/packages/utils/mt-st
ln -s ../../../feeds/packages/kernel/mtd-rw
ln -s ../../../feeds/packages/libs/mtdev
ln -s ../../../feeds/packages/utils/mtools
ln -s ../../../feeds/packages/net/mtr
ln -s ../../../feeds/packages/admin/muninlite
ln -s ../../../feeds/packages/utils/mv88e6xxx_dump
ln -s ../../../feeds/packages/net/mwan3
ln -s ../../../feeds/packages/libs/mxml
ln -s ../../../feeds/packages/libs/nacl
ln -s ../../../feeds/packages/mail/nail
ln -s ../../../feeds/packages/utils/nano
ln -s ../../../feeds/packages/net/natmap
ln -s ../../../feeds/packages/utils/ncdu
ln -s ../../../feeds/packages/net/ncp
ln -s ../../../feeds/packages/libs/neon
ln -s ../../../feeds/packages/net/net-snmp
ln -s ../../../feeds/packages/net/net-tools
ln -s ../../../feeds/packages/admin/netatop
ln -s ../../../feeds/packages/net/netcat
ln -s ../../../feeds/packages/admin/netdata
ln -s ../../../feeds/packages/net/netdiscover
ln -s ../../../feeds/packages/net/netperf
ln -s ../../../feeds/packages/net/netsniff-ng
ln -s ../../../feeds/packages/net/netstinky
ln -s ../../../feeds/packages/net/nfdump
ln -s ../../../feeds/packages/net/nft-qos
ln -s ../../../feeds/packages/libs/nghttp2
ln -s ../../../feeds/packages/net/nginx-util
ln -s ../../../feeds/packages/net/ngircd
ln -s ../../../feeds/packages/net/nlbwmon
ln -s ../../../feeds/packages/libs/nlohmannjson
ln -s ../../../feeds/packages/net/nmap
ln -s ../../../feeds/packages/utils/nnn
ln -s ../../../feeds/packages/libs/npth
ln -s ../../../feeds/packages/net/nsd
ln -s ../../../feeds/packages/libs/nspr
ln -s ../../../feeds/packages/libs/nss
ln -s ../../../feeds/packages/utils/nsutils
ln -s ../../../feeds/packages/net/ntpd
ln -s ../../../feeds/packages/net/ntripcaster
ln -s ../../../feeds/packages/net/ntripclient
ln -s ../../../feeds/packages/net/ntripserver
ln -s ../../../feeds/packages/utils/oath-toolkit
ln -s ../../../feeds/packages/multimedia/oggfwd
ln -s ../../../feeds/packages/net/ola
ln -s ../../../feeds/packages/libs/oniguruma
ln -s ../../../feeds/packages/net/open-iscsi
ln -s ../../../feeds/packages/net/open-isns
ln -s ../../../feeds/packages/utils/open-plc-utils
ln -s ../../../feeds/packages/utils/open2300
ln -s ../../../feeds/packages/libs/openblas
ln -s ../../../feeds/packages/mail/opendkim
ln -s ../../../feeds/packages/utils/opendoas
ln -s ../../../feeds/packages/net/openfortivpn
ln -s ../../../feeds/packages/libs/openpgm
ln -s ../../../feeds/packages/utils/opensc
ln -s ../../../feeds/packages/net/openssh
ln -s ../../../feeds/packages/net/opentracker
ln -s ../../../feeds/packages/net/openvpn
ln -s ../../../feeds/packages/net/openvpn-easy-rsa
ln -s ../../../feeds/packages/utils/openzwave
ln -s ../../../feeds/packages/libs/opus
ln -s ../../../feeds/packages/sound/opus-tools
ln -s ../../../feeds/packages/libs/opusfile
ln -s ../../../feeds/packages/net/ostiary
ln -s ../../../feeds/packages/kernel/ovpn-dco
ln -s ../../../feeds/packages/net/owipcalc
ln -s ../../../feeds/packages/libs/p11-kit
ln -s ../../../feeds/packages/net/p910nd
ln -s ../../../feeds/packages/net/pagekitec
ln -s ../../../feeds/packages/utils/passh
ln -s ../../../feeds/packages/devel/patch
ln -s ../../../feeds/packages/net/pbr
ln -s ../../../feeds/packages/libs/pcapplusplus
ln -s ../../../feeds/packages/utils/pciutils
ln -s ../../../feeds/packages/utils/pcmciautils
ln -s ../../../feeds/packages/libs/pcre2
ln -s ../../../feeds/packages/utils/pcsc-lite
ln -s ../../../feeds/packages/utils/pcsc-tools
ln -s ../../../feeds/packages/net/pen
ln -s ../../../feeds/packages/lang/perl
ln -s ../../../feeds/packages/lang/perl-ack
ln -s ../../../feeds/packages/lang/perl-authen-sasl
ln -s ../../../feeds/packages/lang/perl-cgi
ln -s ../../../feeds/packages/lang/perl-compress-bzip2
ln -s ../../../feeds/packages/lang/perl-dbi
ln -s ../../../feeds/packages/lang/perl-device-serialport
ln -s ../../../feeds/packages/lang/perl-device-usb
ln -s ../../../feeds/packages/lang/perl-encode-locale
ln -s ../../../feeds/packages/lang/perl-file-listing
ln -s ../../../feeds/packages/lang/perl-file-next
ln -s ../../../feeds/packages/lang/perl-file-rsyncp
ln -s ../../../feeds/packages/lang/perl-file-sharedir-install
ln -s ../../../feeds/packages/lang/perl-html-form
ln -s ../../../feeds/packages/lang/perl-html-parser
ln -s ../../../feeds/packages/lang/perl-html-tagset
ln -s ../../../feeds/packages/lang/perl-html-tree
ln -s ../../../feeds/packages/lang/perl-http-cookies
ln -s ../../../feeds/packages/lang/perl-http-daemon
ln -s ../../../feeds/packages/lang/perl-http-date
ln -s ../../../feeds/packages/lang/perl-http-message
ln -s ../../../feeds/packages/lang/perl-http-negotiate
ln -s ../../../feeds/packages/lang/perl-http-server-simple
ln -s ../../../feeds/packages/lang/perl-inline
ln -s ../../../feeds/packages/lang/perl-inline-c
ln -s ../../../feeds/packages/lang/perl-io-html
ln -s ../../../feeds/packages/lang/perl-lockfile-simple
ln -s ../../../feeds/packages/lang/perl-lwp-mediatypes
ln -s ../../../feeds/packages/lang/perl-mail-spamassassin
ln -s ../../../feeds/packages/lang/perl-net-cidr-lite
ln -s ../../../feeds/packages/lang/perl-net-dns
ln -s ../../../feeds/packages/lang/perl-net-http
ln -s ../../../feeds/packages/lang/perl-net-telnet
ln -s ../../../feeds/packages/lang/perl-netaddr-ip
ln -s ../../../feeds/packages/lang/perl-parse-recdescent
ln -s ../../../feeds/packages/lang/perl-parse-yapp
ln -s ../../../feeds/packages/lang/perl-sub-uplevel
ln -s ../../../feeds/packages/lang/perl-test-harness
ln -s ../../../feeds/packages/lang/perl-test-warn
ln -s ../../../feeds/packages/lang/perl-text-csv_xs
ln -s ../../../feeds/packages/lang/perl-try-tiny
ln -s ../../../feeds/packages/lang/perl-uri
ln -s ../../../feeds/packages/lang/perl-www
ln -s ../../../feeds/packages/lang/perl-www-mechanize
ln -s ../../../feeds/packages/lang/perl-www-robotrules
ln -s ../../../feeds/packages/lang/perl-xml-parser
ln -s ../../../feeds/packages/net/phantap
ln -s ../../../feeds/packages/utils/picocom
ln -s ../../../feeds/packages/utils/pigz
ln -s ../../../feeds/packages/net/pingcheck
ln -s ../../../feeds/packages/net/pixiewps
ln -s ../../../feeds/packages/libs/pixman
ln -s ../../../feeds/packages/devel/pkgconf
ln -s ../../../feeds/packages/utils/poemgr
ln -s ../../../feeds/packages/net/polipo
ln -s ../../../feeds/packages/net/port-mirroring
ln -s ../../../feeds/packages/sound/portaudio
ln -s ../../../feeds/packages/libs/postgresql
ln -s ../../../feeds/packages/utils/powertop
ln -s ../../../feeds/packages/net/pppossh
ln -s ../../../feeds/packages/utils/pps-tools
ln -s ../../../feeds/packages/net/pptpd
ln -s ../../../feeds/packages/net/privoxy
ln -s ../../../feeds/packages/utils/procps-ng
ln -s ../../../feeds/packages/utils/progress
ln -s ../../../feeds/packages/net/prosody
ln -s ../../../feeds/packages/libs/protobuf
ln -s ../../../feeds/packages/libs/protobuf-c
ln -s ../../../feeds/packages/net/proxychains-ng
ln -s ../../../feeds/packages/utils/pservice
ln -s ../../../feeds/packages/utils/psmisc
ln -s ../../../feeds/packages/libs/psqlodbc
ln -s ../../../feeds/packages/libs/pthsem
ln -s ../../../feeds/packages/net/ptunnel-ng
ln -s ../../../feeds/packages/libs/pugixml
ln -s ../../../feeds/packages/sound/pulseaudio
ln -s ../../../feeds/packages/utils/pv
ln -s ../../../feeds/packages/lang/python/python-pip-conf
ln -s ../../../feeds/packages/libs/qrencode
ln -s ../../../feeds/packages/utils/quota
ln -s ../../../feeds/packages/net/radsecproxy
ln -s ../../../feeds/packages/net/ratched
ln -s ../../../feeds/packages/net/ratechecker
ln -s ../../../feeds/packages/utils/readsb
ln -s ../../../feeds/packages/net/reaver
ln -s ../../../feeds/packages/libs/redis
ln -s ../../../feeds/packages/net/redsocks
ln -s ../../../feeds/packages/net/remserial
ln -s ../../../feeds/packages/utils/reptyr
ln -s ../../../feeds/packages/utils/rng-tools
ln -s ../../../feeds/packages/net/rp-pppoe
ln -s ../../../feeds/packages/net/rpcbind
ln -s ../../../feeds/packages/libs/rpcsvc-proto
ln -s ../../../feeds/packages/utils/rrdtool1
ln -s ../../../feeds/packages/utils/rtklib
ln -s ../../../feeds/packages/utils/rtl-ais
ln -s ../../../feeds/packages/utils/rtl-sdr
ln -s ../../../feeds/packages/utils/rtl_433
ln -s ../../../feeds/packages/utils/rtty
ln -s ../../../feeds/packages/lang/ruby
ln -s ../../../feeds/packages/net/safe-search
ln -s ../../../feeds/packages/net/samplicator
ln -s ../../../feeds/packages/utils/sane-backends
ln -s ../../../feeds/packages/libs/sbc
ln -s ../../../feeds/packages/devel/scons
ln -s ../../../feeds/packages/utils/screen
ln -s ../../../feeds/packages/utils/sed
ln -s ../../../feeds/packages/utils/semodule-utils
ln -s ../../../feeds/packages/mail/sendmail
ln -s ../../../feeds/packages/net/ser2net
ln -s ../../../feeds/packages/utils/serialconsole
ln -s ../../../feeds/packages/utils/setserial
ln -s ../../../feeds/packages/utils/sexpect
ln -s ../../../feeds/packages/utils/shadow
ln -s ../../../feeds/packages/sound/shairport-sync
ln -s ../../../feeds/packages/sound/shine
ln -s ../../../feeds/packages/net/siit
ln -s ../../../feeds/packages/net/simple-adblock
ln -s ../../../feeds/packages/utils/sipcalc
ln -s ../../../feeds/packages/utils/sispmctl
ln -s ../../../feeds/packages/libs/slang2
ln -s ../../../feeds/packages/utils/slide-switch
ln -s ../../../feeds/packages/net/smartdns
ln -s ../../../feeds/packages/net/smcroute
ln -s ../../../feeds/packages/utils/smstools3
ln -s ../../../feeds/packages/net/snort
ln -s ../../../feeds/packages/net/snort3
ln -s ../../../feeds/packages/net/socat
ln -s ../../../feeds/packages/utils/sockread
ln -s ../../../feeds/packages/net/softethervpn
ln -s ../../../feeds/packages/net/softethervpn5
ln -s ../../../feeds/packages/net/softflowd
ln -s ../../../feeds/packages/net/spawn-fcgi
ln -s ../../../feeds/packages/libs/spdlog
ln -s ../../../feeds/packages/net/speedtest-netperf
ln -s ../../../feeds/packages/libs/speex
ln -s ../../../feeds/packages/libs/speexdsp
ln -s ../../../feeds/packages/utils/spi-tools
ln -s ../../../feeds/packages/libs/spice-protocol
ln -s ../../../feeds/packages/net/spoofer
ln -s ../../../feeds/packages/libs/sqlite3
ln -s ../../../feeds/packages/net/sqm-scripts
ln -s ../../../feeds/packages/net/sqm-scripts-extra
ln -s ../../../feeds/packages/utils/squashfs-tools
ln -s ../../../feeds/packages/utils/ssdeep
ln -s ../../../feeds/packages/utils/sshpass
ln -s ../../../feeds/packages/net/sslh
ln -s ../../../feeds/packages/net/sstp-client
ln -s ../../../feeds/packages/net/static-neighbor-reports
ln -s ../../../feeds/packages/utils/stm32flash
ln -s ../../../feeds/packages/utils/stoken
ln -s ../../../feeds/packages/utils/stress
ln -s ../../../feeds/packages/net/stunnel
ln -s ../../../feeds/packages/admin/sudo
ln -s ../../../feeds/packages/utils/sumo
ln -s ../../../feeds/packages/sound/svox
ln -s ../../../feeds/packages/utils/swig
ln -s ../../../feeds/packages/net/switchdev-poller
ln -s ../../../feeds/packages/net/sysrepo
ln -s ../../../feeds/packages/utils/sysstat
ln -s ../../../feeds/packages/net/tac_plus
ln -s ../../../feeds/packages/libs/taglib
ln -s ../../../feeds/packages/ipv6/tayga
ln -s ../../../feeds/packages/libs/tcp_wrappers
ln -s ../../../feeds/packages/net/tcpproxy
ln -s ../../../feeds/packages/net/tcpreplay
ln -s ../../../feeds/packages/utils/tcsh
ln -s ../../../feeds/packages/net/telnet-bsd
ln -s ../../../feeds/packages/utils/temperusb
ln -s ../../../feeds/packages/libs/tiff
ln -s ../../../feeds/packages/net/tinc
ln -s ../../../feeds/packages/utils/tini
ln -s ../../../feeds/packages/libs/tinycdb
ln -s ../../../feeds/packages/utils/tinyionice
ln -s ../../../feeds/packages/net/tinyproxy
ln -s ../../../feeds/packages/utils/tio
ln -s ../../../feeds/packages/utils/tmux
ln -s ../../../feeds/packages/net/tor
ln -s ../../../feeds/packages/net/tor-hs
ln -s ../../../feeds/packages/net/torsocks
ln -s ../../../feeds/packages/utils/tracertools
ln -s ../../../feeds/packages/net/trafficshaper
ln -s ../../../feeds/packages/utils/tree
ln -s ../../../feeds/packages/utils/triggerhappy
ln -s ../../../feeds/packages/utils/ttyd
ln -s ../../../feeds/packages/multimedia/tvheadend
ln -s ../../../feeds/packages/net/u2pnpd
ln -s ../../../feeds/packages/net/uanytun
ln -s ../../../feeds/packages/utils/ubnt-manager
ln -s ../../../feeds/packages/libs/uci2
ln -s ../../../feeds/packages/net/udhcpsnoop
ln -s ../../../feeds/packages/libs/udns
ln -s ../../../feeds/packages/net/udp-broadcast-relay-redux-openwrt
ln -s ../../../feeds/packages/net/udpspeeder
ln -s ../../../feeds/packages/net/udptunnel
ln -s ../../../feeds/packages/net/udpxy
ln -s ../../../feeds/packages/utils/uhubctl
ln -s ../../../feeds/packages/utils/uledd
ln -s ../../../feeds/packages/net/umurmur
ln -s ../../../feeds/packages/net/unbound
ln -s ../../../feeds/packages/libs/unixodbc
ln -s ../../../feeds/packages/utils/unrar
ln -s ../../../feeds/packages/utils/unzip
ln -s ../../../feeds/packages/net/uradvd
ln -s ../../../feeds/packages/net/usbip
ln -s ../../../feeds/packages/utils/usbmuxd
ln -s ../../../feeds/packages/utils/usbutils
ln -s ../../../feeds/packages/net/usteer
ln -s ../../../feeds/packages/lang/uuid
ln -s ../../../feeds/packages/utils/uvcdynctrl
ln -s ../../../feeds/packages/libs/uw-imap
ln -s ../../../feeds/packages/net/v2ray-geodata
ln -s ../../../feeds/packages/kernel/v4l2loopback
ln -s ../../../feeds/packages/multimedia/v4l2rtspserver
ln -s ../../../feeds/packages/multimedia/v4l2tools
ln -s ../../../feeds/packages/utils/vim
ln -s ../../../feeds/packages/net/vncrepeater
ln -s ../../../feeds/packages/net/vsftpd
ln -s ../../../feeds/packages/net/wakeonlan
ln -s ../../../feeds/packages/utils/watchcat
ln -s ../../../feeds/packages/net/wavemon
ln -s ../../../feeds/packages/libs/websocketpp
ln -s ../../../feeds/packages/net/webui-aria2
ln -s ../../../feeds/packages/net/wget
ln -s ../../../feeds/packages/utils/which
ln -s ../../../feeds/packages/utils/whois
ln -s ../../../feeds/packages/net/wifidog
ln -s ../../../feeds/packages/net/wifischedule
ln -s ../../../feeds/packages/utils/wifitoggle
ln -s ../../../feeds/packages/utils/wipe
ln -s ../../../feeds/packages/net/wsdd2
ln -s ../../../feeds/packages/net/xfrpc
ln -s ../../../feeds/packages/utils/xfsprogs
ln -s ../../../feeds/packages/net/xinetd
ln -s ../../../feeds/packages/net/xl2tpd
ln -s ../../../feeds/packages/libs/xr_usb_serial_common
ln -s ../../../feeds/packages/net/xtables-addons
ln -s ../../../feeds/packages/multimedia/xupnpd
ln -s ../../../feeds/packages/utils/xxhash
ln -s ../../../feeds/packages/utils/xz
ln -s ../../../feeds/packages/libs/yajl
ln -s ../../../feeds/packages/libs/yaml
ln -s ../../../feeds/packages/utils/yara
ln -s ../../../feeds/packages/net/zerotier
ln -s ../../../feeds/packages/utils/zile
ln -s ../../../feeds/packages/libs/zmq
ln -s ../../../feeds/packages/utils/zoneinfo
ln -s ../../../feeds/packages/utils/zsh
ln -s ../../../feeds/packages/utils/zstd
popd
# - end of feed 'packages'

# install packages from feed 'plan44':
# - make sure feed is current
./scripts/feeds update plan44
# - softlink (=install) package dirs
mkdir -p package/feeds/plan44
pushd package/feeds/plan44
ln -s ../../../feeds/plan44/ace-p44script
ln -s ../../../feeds/plan44/hxcmodplayer
ln -s ../../../feeds/plan44/libxm
ln -s ../../../feeds/plan44/mg44
ln -s ../../../feeds/plan44/p44-counter
ln -s ../../../feeds/plan44/p44-ledchain
ln -s ../../../feeds/plan44/p44-stepper
ln -s ../../../feeds/plan44/p44-xx-diy-config
ln -s ../../../feeds/plan44/p44devd
ln -s ../../../feeds/plan44/p44ledchaintest
ln -s ../../../feeds/plan44/p44maintd
ln -s ../../../feeds/plan44/p44mbrd
ln -s ../../../feeds/plan44/p44pagekite
ln -s ../../../feeds/plan44/p44utils-lvgl-sample
ln -s ../../../feeds/plan44/packet_forwarder
ln -s ../../../feeds/plan44/rcswitch
ln -s ../../../feeds/plan44/rtpmidid
ln -s ../../../feeds/plan44/serialfwd
ln -s ../../../feeds/plan44/vdcd
popd
# - end of feed 'plan44'

