#!/bin/sh

# check args
if [ $# -ne 1 -o "0$1" -lt 1 -o "0$1" -gt 3 ]; then
  echo "Usage: $0 <mode>, with mode: 1=reset dS settings, 2=reset network setting, 3=reset both"
  exit 1
fi

# anyway, stop all daemons
/usr/bin/sv stop vdcd  mg44

# reset network settings?
if [ "$1" -eq 2 -o "$1" -eq 3 ]; then
  # copy network settings template from rom
  cp -f /etc/config_p44defaults/network /etc/config/network
  cp -f /etc/config_p44defaults/wireless /etc/config/wireless
fi

# reset other settings?
if [ "$1" -eq 1 -o "$1" -eq 3 ]; then
  # reformat data partition (in case it is corrupted)
  # %%% tbd, remove overlay
  # %%% for now, just erase /flash
  rm -rf /flash/*
fi

# anyway
sync
sleep 2
reboot
